// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGyLyBSOS9_oLoPQTZTGMnBKXti9Yaa8k',
    appId: '1:114011199776:web:218aa4f1ca136994661f45',
    messagingSenderId: '114011199776',
    projectId: 'flipera-dev',
    authDomain: 'flipera-dev.firebaseapp.com',
    storageBucket: 'flipera-dev.firebasestorage.app',
    measurementId: 'G-9KJHD9652B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeKZ2GbVYB92Wz88iElxZZcIQhknNLK20',
    appId: '1:114011199776:android:dd690301793aca12661f45',
    messagingSenderId: '114011199776',
    projectId: 'flipera-dev',
    storageBucket: 'flipera-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBHLws_ijr7omhvWE2exsD1Uwxmbi3Kr0',
    appId: '1:114011199776:ios:ba82f99f2785e892661f45',
    messagingSenderId: '114011199776',
    projectId: 'flipera-dev',
    storageBucket: 'flipera-dev.firebasestorage.app',
    iosBundleId: 'com.example.flipera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBHLws_ijr7omhvWE2exsD1Uwxmbi3Kr0',
    appId: '1:114011199776:ios:ba82f99f2785e892661f45',
    messagingSenderId: '114011199776',
    projectId: 'flipera-dev',
    storageBucket: 'flipera-dev.firebasestorage.app',
    iosBundleId: 'com.example.flipera',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGyLyBSOS9_oLoPQTZTGMnBKXti9Yaa8k',
    appId: '1:114011199776:web:3fedd65ab8afa659661f45',
    messagingSenderId: '114011199776',
    projectId: 'flipera-dev',
    authDomain: 'flipera-dev.firebaseapp.com',
    storageBucket: 'flipera-dev.firebasestorage.app',
    measurementId: 'G-N2KTWNV312',
  );
}
